# This workflow will do a Docker build and then push that image to harbor registory, and also it will modify values.yaml file of our particular helm chart.
# In this action we are using github action build number as a tag of our image.

name: Demo-metabob-Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Get Image Tag
      id: get-tag
      run: |
        type='${{ github.ref_type }}';
        RELEASE_VERSION=${{ github.ref_name }};
        if [[ $type = 'branch' ]] 
        then
            RELEASE_VERSION="$( date -I )-${BUILD_NUMBER}";
        fi
        echo "::set-output name=tag::$RELEASE_VERSION";
      shell: bash
    - name: Print new build number
      run: |
        echo "Build number is $BUILD_NUMBER"
    - uses: actions/checkout@v2
    - name: Login to harbor Container Registry
      uses: docker/login-action@v1
      with:
        registry: harbor.metabob.com
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    - name: Build Docker Image with latest Build Number
      run: |
        word2="harbor.metabob.com/integration/metabob-site:${{ steps.get-tag.outputs.tag }}"
        docker build -t $word2 .
        docker push $word2
