# This workflow will do a docker build image and push to our harbor registory.
name: 'Building and Deploying'

on:
  push:
    branches: [ main ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}} 
  
      - name: Print new build number
        run: |
          echo "Build number is $BUILD_NUMBER"

      - name: Print today's date
        run: |
          today_date="$( date -I )";
          echo " Today's Date is $today_date"
          
      - name: Print image tag number
        run: |
          image_tag = "$( date -I )-${BUILD_NUMBER}"
          echo "Image tag is $image_tag"
