# This workflow will do a docker build image and push to our harbor registory.
name: 'Building and Deploying'

on:
  push:
    branches: [ main ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}} 
  
      - name: Print new build number
        run: |
          echo "Build number is $BUILD_NUMBER"
          
      - name: Get Image Tag
        id: get-tag
        run: |
          type='${{ github.ref_type }}';
          RELEASE_VERSION=${{ github.ref_name }};
          if [[ $type = 'branch' ]] 
          then
              RELEASE_VERSION="$( date -I )-${BUILD_NUMBER}";
          fi
          echo "::set-output name=tag::$RELEASE_VERSION";
        shell: bash
        
      - name: Print today's date
        run: |
          echo " Image tage : ${{ steps.get-tag.outputs.tag }}"
        
