name: 'Building and Pushing Image to Harbor Repository'

on:
  push:
    branches: [ main ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ main ]
    
    
env:
  APP_NAME: metabobapp
  PROJECT_NAME: integration
  REPO_NAME: metabob-site
  CHART_NAME: metabob-site
  CHART_VERSION: 0.1.0
  CHART_REPO_NAME: helm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}} 
          
      - name: Get Image Tag
        id: get-tag
        run: |
          type='${{ github.ref_type }}';
          RELEASE_VERSION=${{ github.ref_name }};
          if [[ $type = 'branch' ]] 
          then
              RELEASE_VERSION="$( date -I )-${BUILD_NUMBER}";
          fi
          echo "::set-output name=tag::$RELEASE_VERSION";
        shell: bash
        
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: harbor.metabob.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}  
          
      - name: Docker image build
        run: |
          echo "Docker images before creation"
          docker images
          docker build -t ${{env.APP_NAME}} .  
          
      - name: Tag Docker Image and Push to Harbor
        run: |
          docker tag ${APP_NAME} harbor.metabob.com/${{env.PROJECT_NAME}}/${{env.REPO_NAME}}:${{ steps.get-tag.outputs.tag }}
          docker push harbor.metabob.com/${{env.PROJECT_NAME}}/${{env.REPO_NAME}}:${{ steps.get-tag.outputs.tag }}
          echo "After tagging"
          docker images
          docker image prune -a -f 
          echo "After pruning"
          docker images
          
