name: 'Building and Pushing Image to Harbor'

on:
  push:
    branches: [ integration ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ integration ]
    
    
env:
  APP_NAME: metabobapp
  PROJECT_ID: integration
  REPO_NAME: metabob-site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}} 
          
      - name: Get Image Tag
        id: get-tag
        run: |
          type='${{ github.ref_type }}';
          RELEASE_VERSION=${{ github.ref_name }};
          if [[ $type = 'branch' ]] 
          then
              RELEASE_VERSION="$( date -I )-${BUILD_NUMBER}";
          fi
          echo "::set-output name=tag::$RELEASE_VERSION";
        shell: bash
        
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: harbor.metabob.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}  
          
          
      - name: Pull docker image
        run: |
          docker pull harbor.metabob.com/chartrepo/nodeapp-helm-charts
          ls -a
             
