name: 'Building and Pushing Image to Harbor'

on:
  push:
    branches: [ main ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ main ]
    
    
env:
  APP_NAME: metabobapp
  PROJECT_ID: integration
  REPO_NAME: metabob-site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}} 
          
      - name: Get Image Tag
        id: get-tag
        run: |
          type='${{ github.ref_type }}';
          RELEASE_VERSION=${{ github.ref_name }};
          if [[ $type = 'branch' ]] 
          then
              RELEASE_VERSION="$( date -I )-${BUILD_NUMBER}";
          fi
          echo "::set-output name=tag::$RELEASE_VERSION";
        shell: bash
        
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: harbor.metabob.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}  
          
      - name: Docker image build
        run: |
          docker build -t ${{env.APP_NAME}} .  
          
      - name: Tag Docker Image and Push to Harbor
        run: |
          docker tag ${APP_NAME} harbor.metabob.com/${{env.PROJECT_ID}}/${{env.REPO_NAME}}:${{ steps.get-tag.outputs.tag }}
          docker push harbor.metabob.com/${{env.PROJECT_ID}}/${{env.REPO_NAME}}:${{ steps.get-tag.outputs.tag }}
          docker rmi -f ${{env.APP_NAME}}
          docker rmi -f harbor.metabob.com/${{env.PROJECT_ID}}/${{env.REPO_NAME}}:${{ steps.get-tag.outputs.tag }}  
          
          
      - name: Helm and plugin Install
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm plugin install https://github.com/chartmuseum/helm-push
          
          
      - name: Pull Helm chart from Harbor
        run: |
          helm repo add harbor https://harbor.metabob.com/chartrepo/helm --username ${{ secrets.HARBOR_USERNAME }}  --password ${{ secrets.HARBOR_PASSWORD }}
          helm pull harbor/metabob-site
          
      - name: Update Image Tag in Helm chart
        run: |
          tar xvfz metabob-site-0.1.0.tgz
          cd metabob-site
          sed -i 's/tag:.*/tag: "${{ steps.get-tag.outputs.tag }}"/g' values.yaml
          cat values.yaml
          cd ../
          tar -zcvf metabob-site.tar.gz metabob-site
          
      - name: Pushing Updated helm chart in Harbor
        run: |
          helm cm-push -f metabob-site.tar.gz harbor
        
