name: 'Building and Deploying'

on:
  push:
    branches: [ main ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ main ]
    
    
env:
  ## Sets environment variable
  API_KEY: ABC1234    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: step 1
        run: echo "The API key is:${{env.API_KEY}}"  	
