name: 'Building and Pushing Image to Harbor Repository'

on:
  push:
    branches: [ main ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ main ]
    
    
env:
  APP_NAME: metabobapp
  PROJECT_NAME: integration
  REPO_NAME: metabob-site
  CHART_NAME: metabob-site
  CHART_VERSION: 0.1.0
  CHART_REPO_NAME: helm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}} 
          
      - name: Get Image Tag
        id: get-tag
        run: |
          type='${{ github.ref_type }}';
          RELEASE_VERSION=${{ github.ref_name }};
          if [[ $type = 'branch' ]] 
          then
              RELEASE_VERSION="$( date -I )-${BUILD_NUMBER}";
          fi
          echo "::set-output name=tag::$RELEASE_VERSION";
        shell: bash
        
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: harbor.metabob.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}          
          
      - name: Helm and helm-push plugin Install
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm plugin install https://github.com/chartmuseum/helm-push
          
          
      - name: Pull Helm chart from Harbor
        run: |
          echo "Before pull"
          ls -a
          helm repo add harbor https://harbor.metabob.com/chartrepo/${{env.CHART_REPO_NAME}} --username ${{ secrets.HARBOR_USERNAME }}  --password ${{ secrets.HARBOR_PASSWORD }}
          helm pull harbor/${{env.CHART_NAME}}
          echo "After pull"
          ls -a
          
      - name: Update Image Tag in Helm chart
        run: |
          tar xvfz ${{env.CHART_NAME}}-${{env.CHART_VERSION}}.tgz chart
          cd chart
          sed -i 's/tag:.*/tag: "${{ steps.get-tag.outputs.tag }}"/g' values.yaml
          cat values.yaml
          cd ../
          tar -zcvf chart.tar.gz chart
          
      - name: Pushing Updated helm chart in Harbor
        run: |
          helm cm-push -f chart.tar.gz harbor
        
      - name: Cleanup 
        run: |
          rm -rf *
