name: 'Building and Pushing Image to Harbor Repo'

on:
  push:
    branches: [ main ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ main ]
    
    
env:
  APP_NAME: metabobapp
  PROJECT_NAME: integration
  REPO_NAME: metabob-site
  CHART_NAME: metabob-site
  CHART_REPO_NAME: helm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}} 
          
      - name: Get Image Tag
        id: get-tag
        run: |
          type='${{ github.ref_type }}';
          RELEASE_VERSION=${{ github.ref_name }};
          if [[ $type = 'branch' ]] 
          then
              RELEASE_VERSION="$( date -I )-${BUILD_NUMBER}";
          fi
          echo "::set-output name=tag::$RELEASE_VERSION";
        shell: bash
        
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: harbor.metabob.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}  
          
      - name: Docker image build
        run: |
          docker build -t ${{env.APP_NAME}} .  
          
      - name: Tag Docker Image and Push to Harbor
        run: |
          docker tag ${APP_NAME} harbor.metabob.com/${{env.PROJECT_NAME}}/${{env.REPO_NAME}}:${{ steps.get-tag.outputs.tag }}
          docker push harbor.metabob.com/${{env.PROJECT_NAME}}/${{env.REPO_NAME}}:${{ steps.get-tag.outputs.tag }}
          docker image prune -a -f 
          docker images 
           
      - name: Helm and helm-push plugin Install
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm plugin install https://github.com/chartmuseum/helm-push
          
          
      - name: Pull Helm chart from Harbor
        run: |
          helm repo add harbor https://harbor.metabob.com/chartrepo/${{env.CHART_REPO_NAME}} --username ${{ secrets.HARBOR_USERNAME }}  --password ${{ secrets.HARBOR_PASSWORD }}
          helm pull harbor/${{env.CHART_NAME}}
          
      - name: Update Image Tag and chart version in Helm chart
        run: |
          mkdir -p ${{env.CHART_NAME}}
          tar xvfz ${{env.CHART_NAME}}-*.tgz ${{env.CHART_NAME}}/
          ls -a
          cd ${{env.CHART_NAME}}
          sed -i 's/tag:.*/tag: "${{ steps.get-tag.outputs.tag }}"/g' values.yaml
          sed -i 's/version:.*/version: "${{ steps.get-tag.outputs.tag }}"/g' Chart.yaml
          sed -i 's/appVersion:.*/appVersion: "${{ steps.get-tag.outputs.tag }}"/g' Chart.yaml
          cd ../
          tar -zcvf ${{env.CHART_NAME}}.tar.gz ${{env.CHART_NAME}}
          
      - name: Pushing Updated helm chart in Harbor
        run: |
          helm cm-push -f ${{env.CHART_NAME}}.tar.gz harbor
        
      - name: Files Cleanup 
        run: |
          rm -rf *
